### ISSUE TITLE
Получить различные результаты библиотеки

### ISSUE THREAD

**Issue by SmirnovEgorRu** [angelaburova/bigARTM#5]
Когда сделаем свою регуляризацию, нам надо будет с чем-то сравнивать. Для этого нам надо получить результаты с **различными входными данными** до и после **оптимальной** регуляризации.

Для начала надо определиться с оптимальным количеством тем (оно мб и не 12). Для этого на текущей (хорошей, со всеми стоп словами и лемматизацией) подобрать это число вручную. И потом это количество использовать для всех.

От запуска к запуску менять стоит только файлик out.txt, сам скрипт запуска остается такой же.
Что понимается под оптимальной регуляризацией? То, что слова в топе адекватные, пусть матрицы и не разреженные, но должно быть понятно какая-то это тема.
Специально разделил запускающий скрипт. Это нужно что бы экономить время на подборе коэффициента регуляризации.
run.py - просто обучает модель без регуляризации и сохраняет ее.
run_for_reg.py - загружает модель и обучает с регуляризацией.

Пример хорошего результата, хоть и с меньшей разреженностью и плохого, но с большей.
[пример.txt](https://github.com/angelaburova/bigARTM/files/998490/default.txt)

Какие случае стоит проверить?

1. Вообще без лемматизации и удаления стоп-слов. Для этого запустить merge.py на папку serarate.
2. Отключить удаление стоп-слов, но оставить лемматизацию. Для этого закомментить строчки 60 - 61 в скрипте correct_text.py.
3. Отключить лемматизцаию, но оставить стоп слова. Закомментить строчки 56-58 в скрипте correct_text.py.
4. Использовать лемматизацию, но теперь использовать словарик на 10к стоп-слов. Для этого поменять путь до стоп-слов в 6 строчке correct_text.py.
5. Найти файлик out.txt, полученный после лемматизации и стоп слов на сервисе. Посмотреть какие результаты там. Думаю, можно найти в истории гита.
6. Не делать инициалы через подчеркивание, но оставить все остальные правки. Для этого в с скрипте separate_to_articles.py закомментить строчку 160.
7. Оставить только одну модальность - текст. Тут надо будет убрать из merge запись авторов и тем и немного поменять запуск библиотеки.

Для каждого случая получится файлик с топом слов до и после регуляризации. Коэффициенты разреженности тоже нужны. Все эти файлики назвать и положить на гит.

**Comment by angelaburova** [comment]
насчет предыдущей версии out что -то я не уверена что сохранился, не нашла
но это не точно
ну скрины есть:D где нибудь в истории нашей переписки

**Comment by SmirnovEgorRu** [comment]
положил out в папку со старыми файлами
